// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kohdzjsycugiflhibndu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvaGR6anN5Y3VnaWZsaGlibmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTI2NDMsImV4cCI6MjA3Mjk4ODY0M30.8A5k7w_dlMTJ2gpdQtxejDJixFYYfAfDDInLW2n-fY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});